#spring.application.name=identity_service
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    jpa tu tao table trong sql chi dung khi hc spring boot
jwt:
  SignKey: "INFljS5rAAOHIPA3tgEULE9l1f7qRw1o7Vp0DJkACPHm2sVDPqrjYBNceAqltbXS"
  valid-duration: 20 # token het han sau 10 s
  refreshable-duration: 120 #co the refresh trong 120 s

# 10s dc 5 request
resilience4j.ratelimiter.instances.apiLimit:
  limitForPeriod: 5
  limitRefreshPeriod: 10s
  timeoutDuration: 0
